<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'nguyenanhung\\MyNuSOAP\\' => array($vendorDir . '/nguyenanhung/nusoap/src'),
    'nguyenanhung\\MyFixNuSOAP\\' => array($vendorDir . '/nguyenanhung/nusoap/fixed'),
);
