<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit65998413ba64fcb3e784e88aa96075ef
{
    public static $files = array (
        'e446537dc177b4796a93253d3543726a' => __DIR__ . '/..' . '/nguyenanhung/nusoap/helpers/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'n' => 
        array (
            'nguyenanhung\\MyNuSOAP\\' => 22,
            'nguyenanhung\\MyFixNuSOAP\\' => 25,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'nguyenanhung\\MyNuSOAP\\' => 
        array (
            0 => __DIR__ . '/..' . '/nguyenanhung/nusoap/src',
        ),
        'nguyenanhung\\MyFixNuSOAP\\' => 
        array (
            0 => __DIR__ . '/..' . '/nguyenanhung/nusoap/fixed',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit65998413ba64fcb3e784e88aa96075ef::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit65998413ba64fcb3e784e88aa96075ef::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit65998413ba64fcb3e784e88aa96075ef::$classMap;

        }, null, ClassLoader::class);
    }
}
